### ISSUE TITLE
Spring 2016 Not showing up

### ISSUE THREAD

**Issue by scottopell** [Purdue-io/WebApp#4]
Courses and schedules are out: https://esa-oas-prod.itap.purdue.edu:9011/prod/bzwsrch.p_search_schedule?term=201620&subject=CS&cnbr=42200&schd_type=LEC

but don't see it on purdue.io.

**Comment by haydenmc** [comment]
Looking into it, thanks for the report!

**Comment by haydenmc** [comment]
Tracking this here, as this is an API issue with CatalogSync:
https://github.com/Purdue-io/PurdueApi/issues/9
